Fix Sorting Algorithm Bug
fadhilyori/subping pull request #13
Opened 2023-07-03 10:03 UTC by izzatbey

Solution of the Sorting Algorithm bug in subping result

2023-07-03 12:08 UTC, fadhilyori requested changes

2023-07-03 12:08 UTC, fadhilyori commented on cmd/subping/main.go
> +	fmt.Println("-------------------------------------")
Why did you reduce the length of the table?

2023-07-03 12:08 UTC, fadhilyori commented on cmd/subping/main.go
> +		fmt.Printf("| %-15s | %-15s |\n", ipString, stats.AvgRtt.String())
Why did you reduce the length of the table?

2023-07-03 12:08 UTC, fadhilyori commented on cmd/subping/main.go
> +	fmt.Println("-------------------------------------")
Why did you reduce the length of the table?

2023-07-03 12:11 UTC, izzatbey commented on cmd/subping/main.go
> +		fmt.Printf("| %-15s | %-15s |\n", ipString, stats.AvgRtt.String())
sorry i forgot to change back... it just myself understanding the table... i'll bring it back

2023-07-03 12:56 UTC, fadhilyori approved these changes
lgtm

2023-07-04 04:24 UTC, fadhilyori approved these changes
lgtm

2023-07-04 04:24 UTC, merged